jobs:
  - name: dv-man
    type: manifest
    steps:
      - IN: dv-image
        pull: false

  - name: multi-manifest
    type:  deploy
    steps:
      - IN: dv-man

  - name: release-one
    type: release
    steps:
      - IN: dv-man
      - TASK: managed
        bump: major

  - name: infra-provision
    type: runSh
    steps:
      - IN: dv-man
      - IN: newssh
      - TASK:
        - script: echo "integration name------>-"$OLDSSHKEY_NAME
        - script: echo "public key------>-"$OLDSSHKEY_INTEGRATION_PUBLICKEY
        - script: echo "private key----->-"$OLDSSHKEY_INTEGRATION_PRIVATEKEY
        - script: echo "public key path----->-"$OLDSSHKEY_PUBLIC_KEY_PATH
        - script: echo "private key path------->-"$OLDSSHKEY_PRIVATE_KEY_PATH
        
