jobs:
  - name: dv-man
    type: manifest
    steps:
      - IN: dv-image
        pull: false

  - name: multi-manifest
    type:  deploy
    steps:
      - IN: dv-man

  - name: release-one
    type: release
    steps:
      - IN: dv-man
      - TASK: managed
        bump: major

  - name: infra-provision
    type: runSh
    steps:
      - IN: dv-man
      - IN: newssh
      - TASK:
        - script: echo "integration name------>-"$NEWSSH_NAME
        - script: echo "public key------>-"$NEWSSH_INTEGRATION_PUBLICKEY
        - script: echo "private key----->-"$NEWSSH_INTEGRATION_PRIVATEKEY
        - script: echo "public key path----->-"$NEWSSH_PUBLIC_KEY_PATH
        - script: echo "private key path------->-"$NEWSSH_PRIVATE_KEY_PATH
        
  - name: pem
    type: runSh
    steps:
      - IN: dv-man
      - IN: pemkey
      - TASK:
        - script: cd IN/
        - script: cd pemkey/
        - script: ls -a
        - script: cat pemkey_key.pem
        - script: echo "<---------INTEGRATION NAME------>"
        - script: echo $PEMKEY_NAME
        - script: echo "<---------key------>"
        - script: echo $PEMKEY_INTEGRATION_KEY
        - script: echo "<-------key path----->"
        - script: echo $PEMKEY_PATH
        
  - name: pemkeytest1
    type: runSh
    steps:
      - IN: dv-man
      - IN: pemkeytest1
      - TASK:
        - script: cd IN/
        - script: cd pemkeytest/
        - script: ls -a
        - script: cat pemkeytest_key.pem
        - script: echo "<---------INTEGRATION NAME------>"
        - script: echo $PEMKEYTEST_NAME
        - script: echo "<---------key------>"
        - script: echo $PEMKEYTEST_INTEGRATION_KEY
        - script: echo "<-------key path----->"
        - script: echo $PEMKEYTEST_PATH
