jobs:
  - name: dv-man
    type: manifest
    steps:
      - IN: dv-image
        pull: false

  - name: multi-manifest
    type:  deploy
    steps:
      - IN: dv-man

  - name: release-one
    type: release
    steps:
      - IN: dv-man
      - TASK: managed
        bump: major

  - name: infra-provision
    type: runSh
    steps:
      - IN: dv-man
      - IN: newssh
      - IN: ssh
      - IN: keytest
      - TASK:
        - script: echo "integration name------>-"$NEWSSH_NAME
        - script: echo "public key------>-"$NEWSSH_INTEGRATION_PUBLICKEY
        - script: echo "private key----->-"$NEWSSH_INTEGRATION_PRIVATEKEY
        - script: echo "public key path----->-"$NEWSSH_PUBLIC_KEY_PATH
        - script: echo "private key path------->-"$NEWSSH_PRIVATE_KEY_PATH
        - script: echo "integration name------>-"$SSH_NAME
        - script: echo "public key------>-"$SSH_INTEGRATION_PUBLICKEY
        - script: echo "private key----->-"$SSH_INTEGRATION_PRIVATEKEY
        - script: echo "public key path----->-"$SSH_PUBLIC_KEY_PATH
        - script: echo "private key path------->-"$SSH_PRIVATE_KEY_PATH
        - script: echo "integration name------>-"KEYTEST_NAME
        - script: echo "public key------>-"$KEYTEST_INTEGRATION_PUBLICKEY
        - script: echo "private key----->-"$KEYTEST_INTEGRATION_PRIVATEKEY
        - script: echo "public key path----->-"$KEYTEST_PUBLIC_KEY_PATH
        - script: echo "private key path------->-"$KEYTEST_PRIVATE_KEY_PATH
  - name: pem
    type: runSh
    steps:
      - IN: dv-man
      - IN: pemkey
      - TASK:
        - script: cd IN/
        - script: cd pemkey/
        - script: ls -a
        - script: cat pemkey_key.pem
        - script: echo "<---------INTEGRATION NAME------>"
        - script: echo $PEMKEY_NAME
        - script: echo "<---------key------>"
        - script: echo $PEMKEY_INTEGRATION_KEY
        - script: echo "<-------key path----->"
        - script: echo $PEMKEY_PATH
        
  - name: N1
    type: runSh
    steps:
      - IN: dv-man
      - IN: pemactual
      - TASK:
        - script: cd IN/
        - script: cd pemactual/
        - script: ls -a
        - script: cat pemactual_key.pem
        - script: echo "<---------INTEGRATION NAME------>"
        - script: echo $PEMACTUAL_NAME
        - script: echo "<---------key------>"
        - script: echo $PEMACTUAL_INTEGRATION_KEY
        - script: echo "<-------key path----->"
        - script: echo $PEMACTUAL_PATH
